### ISSUE TITLE
"Go to definition" for Openhab2 provided types / methods fails

### ISSUE THREAD

**Issue by timcharper** [openhab/openhab-vscode#131]
I'd like to look at the docstring from some Openhab2 provided type. When I right click on the type, and select the "go to definition", I get an error:

![jan-13-2019 17-18-04](https://user-images.githubusercontent.com/183/51092680-4ba1cf80-1757-11e9-9b89-2a5be839018f.gif)

```
[Error - 5:16:34 PM] Request textDocument/definition failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.RuntimeException: Cannot create a resource for 'java:/Objects/org.eclipse.smarthome.model.script.actions.Timer'; a registered resource factory is needed
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at org.eclipse.xtext.ide.server.concurrent.ReadRequest.lambda$run$0(ReadRequest.java:43)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Cannot create a resource for 'java:/Objects/org.eclipse.smarthome.model.script.actions.Timer'; a registered resource factory is needed
	at org.eclipse.xtext.resource.XtextResourceSet.getResource(XtextResourceSet.java:262)
	at org.eclipse.xtext.ide.server.ProjectManager.getResource(ProjectManager.java:172)
	at org.eclipse.xtext.ide.server.WorkspaceManager.doRead(WorkspaceManager.java:276)
	at org.eclipse.xtext.ide.server.findReferences.WorkspaceResourceAccess.readOnly(WorkspaceResourceAccess.java:42)
	at org.eclipse.xtext.ide.server.symbol.DocumentSymbolService.doRead(DocumentSymbolService.java:314)
	at org.eclipse.xtext.ide.server.symbol.DocumentSymbolService.getDefinitions(DocumentSymbolService.java:110)
	at org.eclipse.xtext.ide.server.symbol.DocumentSymbolService.getDefinitions(DocumentSymbolService.java:91)
	at org.eclipse.xtext.ide.server.LanguageServerImpl.lambda$definition$31(LanguageServerImpl.java:567)
	at org.eclipse.xtext.ide.server.WorkspaceManager.doRead(WorkspaceManager.java:283)
	at org.eclipse.xtext.ide.server.LanguageServerImpl.definition(LanguageServerImpl.java:569)
	at org.eclipse.xtext.ide.server.LanguageServerImpl.lambda$definition$30(LanguageServerImpl.java:550)
	at org.eclipse.xtext.ide.server.concurrent.ReadRequest.lambda$run$0(ReadRequest.java:37)
	... 4 more

```

## Steps to Reproduce (for Bugs)

Given a visual studio code instance connecting to a remote Openhab2 PI instance, editing files over a Samba share:

1. Create a new rule
2. Add a line: `val Timer my_timer = null`
3. Right-click on "Timer" and click "go to definition"

## Your Environment

* OpenHab 2.4.0
* VSC OpenHab2 plugin version 0.4.1
* Mac OS; OpenHab2 is running on a PI.
* Editing rule files over a samba share.

**Comment by SamuelBrucksch** [comment]
This is an issue with the openhab lsp and not vscode extension. Will lookup the repo for you and post it here, so you can open an issue there.

**Comment by timcharper** [comment]
Okay, thanks @SamuelBrucksch ; I guess you didn't find the lsp repo? Is it here? https://github.com/eclipse/smarthome

**Comment by kubawolanin** [comment]
Thanks @timcharper for the submission.
Since the ESH repository is no longer maintained, and its codebase moved to [openhab/openhab-core](https://github.com/openhab/openhab-core), we should submit server-side LSP related issues there.

FYI: You can find LSP code here:
https://github.com/openhab/openhab-core/tree/master/bundles/org.openhab.core.model.lsp

Cheers
