### ISSUE TITLE
Error: Could not get valid data from REST API

### ISSUE THREAD

**Issue by fwolter** [openhab/openhab-vscode#201]
I'm getting the following error, when connecting to my openHAB instance, running behind a nginx reverse proxy with Basic Auth and Letsencrypt with redirection to SSL:

```
Error: Could not get valid data from REST API
    at U._callback (c:\Users\fab\.vscode\extensions\openhab.openhab-0.7.0\serverJS\out\LSPServer.js:135:130206)
    at U.t._callback.t.callback.t.callback (c:\Users\fab\.vscode\extensions\openhab.openhab-0.7.0\serverJS\out\LSPServer.js:195:5603)
    at U.emit (events.js:203:13)
    at U.<anonymous> (c:\Users\fab\.vscode\extensions\openhab.openhab-0.7.0\serverJS\out\LSPServer.js:195:18463)
    at U.emit (events.js:203:13)
    at IncomingMessage.<anonymous> (c:\Users\fab\.vscode\extensions\openhab.openhab-0.7.0\serverJS\out\LSPServer.js:195:17295)
    at Object.onceWrapper (events.js:291:20)
    at IncomingMessage.emit (events.js:208:15)
    at endReadableNT (_stream_readable.js:1168:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

When looking into the TCP stream, I see VSCode gets redirected via port 80 to 443 and then continues encrypted. The connection to the LSP on port 5007 seems to work. Accessing the REST API via browser do work and connecting VSCode to the REST API of my local openHAB instance work, too.

This is my config:
![grafik](https://user-images.githubusercontent.com/1894841/79124806-666d5480-7d9d-11ea-8368-38c6f4cbaf14.png)

Tried already port 443 or connection by IP address.

VSCode openHAB 0.7.0
openHAB 2.5.3

**Comment by Confectrician** [comment]
It seems that the local LSP server cant handle the basic auth connection.
IT seems to not get dactivated fully, when remote lsp is active.

Reference:
https://github.com/openhab/openhab-vscode/blob/master/serverJS/src/ItemCompletion/ItemCompletionProvider.js#L153

This seems like a hardcoded url.

**Comment by fwolter** [comment]
I just wanted to reproduce the error, but now, everything works. I didn't change anything by intention... Observing it.

**Comment by Confectrician** [comment]
Thanks for the Feedback.
I have a guess then.

Maybe we have some cached data that caused trouble.
I recently read from bug reports which seem to solve themselves.
Maybe we should check if we can provide some sort of caching override for settings.

**Comment by KHOne23** [comment]
I am faceing the same Problem when i have installed the Amazon Echo Control Binding. When i deinstall it everything works fine. when i reinstall it i am faceing this error

**Comment by heimerle** [comment]
@Confectrician basically i am facing the same problem, but i can confirm the hard coded URL problem, when adding /rest/items to the openHab.host config, at least the items occur in VS Code, for things i am still getting the error message "Error while connecting to REST API"

**Comment by pgfeller** [comment]
@fwolter, @heimerle & @KHOne23 

Hi all,

do you still use the extension and DSL. I'm cleaning up the backlog and try to assign the priorities accordingly. As I do not use DSL I would need to collaborate with an DSL extension user to isolate and fix the problem.

with kind regards,
Patrik

**Comment by fwolter** [comment]
I have a working OH setup and I apply changes so seldom that I use a normal text editor. So, I don't use it anymore.

**Comment by pgfeller** [comment]
> I have a working OH setup and I apply changes so seldom that I use a normal text editor. So, I don't use it anymore.

Thank you for the feedback! As the extension was dormant this helps me to set priorities. I'll put focus on GraalVM languages at the moment.

**Comment by KHOne23** [comment]
> [@fwolter](https://github.com/fwolter), [@heimerle](https://github.com/heimerle) & [@KHOne23](https://github.com/KHOne23)
> do you still use the extension and DSL. I'm cleaning up the backlog and try to assign the priorities accordingly. As I do not use DSL I would need to collaborate with an DSL extension user to isolate and fix the problem.

I don´t use Openhab anymore, moved to Home Assistant year ago
