### ISSUE TITLE
Visual Studio 2017

### ISSUE THREAD

**Issue by boerreth** [openhab/openhab-vscode#28]
I get problems on 2017. I doubleclick  and then I get:
10.7.17 16:41:30 - Found installed product - Visual Studio Enterprise 2017
10.7.17 16:41:30 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by MHerbst** [comment]
This is an extension for Visual Studio **Code** and not Visual Studio 2017 (or older). Unfortunately, Microsoft uses the same file extension for both types of installer packages.
To install the extension in Visual Studio Code please follow the instructions here: https://github.com/openhab/openhab-vscode/releases.

**Comment by kubawolanin** [comment]
Thank you @MHerbst! Closing this issue.
